name: Hammock
baseurl: /hammock
description: Purely functional HTTP client
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.9.0+6-3a9b37c2-SNAPSHOT
org: com.pepegar
markdown: kramdown
